# Generated by Django 5.2.14 on 2026-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('leave_reason', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
